CREATE TABLE [dbo].[Order]
(
	[OrderID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CustID] INT NULL, 
    [CarID] INT NULL
)
CONSTRAINT fk_orders_cust_id
 FOREIGN KEY (CustId)
 REFERENCES Customer (CustId)
 ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_orders_inv_id
 FOREIGN KEY (CarId)
 REFERENCES Inventory (CarId)
 ON DELETE CASCADE
ON UPDATE CASCADE